### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by chavenor** [StackStorm-Exchange/stackstorm-nest#2]
Is it possible Nest has changed the API to need an Oath token now?

The config file is filled out with the proper credentials. 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/stackstorm/virtualenvs/nest/lib/python2.7/site-packages/nest/nest.py", line 1666, in structures
    for stid in self._status[STRUCTURES]]
  File "/opt/stackstorm/virtualenvs/nest/lib/python2.7/site-packages/nest/nest.py", line 1616, in _status
    value = self._get("/")
  File "/opt/stackstorm/virtualenvs/nest/lib/python2.7/site-packages/nest/nest.py", line 1599, in _get
    return self._request('GET', path)
  File "/opt/stackstorm/virtualenvs/nest/lib/python2.7/site-packages/nest/nest.py", line 1582, in _request
    raise AuthorizationError(response)
nest.nest.AuthorizationError: Authorization Failed
```

**Comment by LindsayHill** [comment]
Yes, looks like this is an issue with newer version of `python-nest`

> NOTE The 3.x version uses the Nest official api. As such, some functionality was removed as it is not available. To keep the old version and functionality, make sure to set your requirements to python-nest<3.0.

(from https://github.com/jkoelker/python-nest/tree/master).

For now, will create PR to pin python-nest version.
